name: uitb_gymnasium
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.05.30=h06a4308_0
  - cffi=1.15.1=py311h409f033_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.7=py311ha3edf6b_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.7=py311hcafe171_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - freetype=2.12.1=hca18f0e_1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - ipykernel=6.23.1=pyh210e3f2_0
  - ipympl=0.9.3=pyhd8ed1ab_0
  - ipython=8.14.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.6=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h38be061_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_1
  - kiwisolver=1.4.4=py311h4dd048b_1
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=17_linux64_openblas
  - libdeflate=1.18=h0b41bf4_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h753d276_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=ha587672_6
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib-base=3.7.1=py311h8597a09_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy=1.24.3=py311h64a7726_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py311h0b84326_1
  - pip=23.1.2=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py311h2582759_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.3=h2755cc3_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyzmq=25.1.0=py311h75c88c4_0
  - readline=8.2=h8228510_1
  - scipy=1.10.1=py311h64a7726_3
  - setuptools=67.8.0=py311h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py311h1f0f07a_1
  - tk=8.6.12=h27826a3_0
  - tornado=6.3.2=py311h459d7ec_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.7=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py311hbe0fcd7_1
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - appdirs==1.4.4
      - cachetools==5.3.0
      - certifi==2022.12.7
      - click==8.1.3
      - cloudpickle==2.2.1
      - cmake==3.26.3
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - evdev==1.6.1
      - farama-notifications==0.0.4
      - filelock==3.12.0
      - fonttools==4.39.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.5.9
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - gymnasium==0.28.1
      - imageio==2.28.1
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - lit==16.0.2
      - markdown==3.4.3
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - mujoco==2.3.5
      - networkx==3.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - odfpy==1.4.1
      - opencv-python==4.7.0.72
      - pandas==2.0.1
      - pathtools==0.1.2
      - protobuf==4.22.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygame==2.4.0
      - pynput==1.7.6
      - pyopengl==3.1.6
      - python-xlib==0.33
      - pyyaml==6.0
      - requests==2.29.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - ruamel-yaml==0.17.22
      - seaborn==0.11.2
      - sentry-sdk==1.21.1
      - setproctitle==1.3.2
      - smmap==5.0.0
      - stable-baselines3==2.0.0a5
      - statannot==0.2.3
      - statannotations==0.5.0
      - sympy==1.11.1
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - torch==2.0.0
      - triton==2.0.0
      - typing-extensions==4.5.0
      - urllib3==1.26.15
      - wandb==0.15.2
      - werkzeug==2.3.3
      - xmltodict==0.13.0
prefix: /opt/conda/envs/uitb_gymnasium
