simulator_name: beatsvr_early_termination_bimanual_neural_1e2_contact
project: unity

simulation:
  bm_model:
    cls: MoblArmsBimanualMotor
    kwargs:
      shoulder_variant: none
      #skull_rotation: [0.9961947, 0, 0, -0.0871557]
      effort_model:
        cls: Neural
        kwargs:
          weight: 1e-2
  task:
    cls: Unity
    kwargs:
#      app_args: ["-right_hand_only"]
      unity_executable: apps/beats-vr-linux/build.x86_64
      standalone: true # set to False for debugging (open the app in Unity editor)
      # port: 5555 # uncomment for debugging (connects to this port instead of finding a random open one)
      time_scale: 5
      max_episode_length_seconds: 10
      gear: oculus-quest-1
      left_controller_enabled: true
      left_controller_body: hand_l
      left_controller_relpose: [-0.06777743, 0.02224773, 0.00873933, 0.5382897, 0.72938,
        -0.3715395, 0.200518]
      right_controller_body: hand_r
      right_controller_relpose: [-0.06694103, -0.00423279, 0.00806701, 0.79349534,
        0.49238653, -0.24941408, 0.256346]
      headset_body: skull
      headset_relpose: [-0.10703, 0.001594, -0.19141, 0.7071068, 0.7071068, 0, 0]
  perception_modules:
  - cls: vision.UnityHeadset
    kwargs:
      resolution: [120, 80]   # must match dimensions used in unity
      channels: [0, 2]
      buffer: 0.2
      use_buffer_difference: false
  - cls: proprioception.BasicWithEndEffectorPosition
    kwargs:
      end_effector: [[geom, controller-right], [geom, controller-left]]
  run_parameters:
    action_sample_freq: 20
    info_keywords: [[AccumulatedErrors, final], [AccumulatedCorrectSlices, final]]

rl:
  algorithm: PPO
  policy_type: policies.MultiInputActorCriticPolicyTanhActions
  policy_kwargs:
    activation_fn: torch.nn.LeakyReLU
    net_arch: [256, 256]
    log_std_init: 0.0
    features_extractor_class: feature_extractor.FeatureExtractor
    normalize_images: false
  lr:
    function: schedule.linear_schedule
    kwargs:
      initial_value: 5e-5
      min_value: 1e-7
      threshold: 0.8
  total_timesteps: 100_000_000
  device: cuda
  num_workers: 10
  nsteps: 4000
  batch_size: 1000
  target_kl: 1.0
  save_freq: 5_000_000
version: 1.1.0
package_name: beatsvr_early_termination_bimanual_neural_1e2_contact
gym_name: uitb:beatsvr_early_termination_bimanual_neural_1e2_contact-v0
built: '2024-03-01 08:38:22'
