run_name: "mobl_arms_index_remote_driving"

simulation:
  bm_model:
    cls: "MoblArmsIndex"
    kwargs:
      shoulder_variant: "none"
  task:
    cls: "RemoteDriving"
    kwargs:
      end_effector: "hand_2distph"
      car_velocity_threshold: 0
      episode_length_seconds: 10
      episode_length_seconds_extra_time: 0
      reward_function:
        cls: "NegativeExpDistance"
  perception_modules:
    - cls: "vision.FixedEye"
      kwargs:
        resolution: [120, 80]
        channels: [0]
        buffer: 0.1
        pos: "0 0 1.2"
        quat: "0.583833 0.399104 -0.399421 -0.583368"
    - cls: "proprioception.BasicWithEndEffectorPosition"
      kwargs:
        end_effector: ["geom", "hand_2distph"]
    - cls: "tactile.RectangularCuboidGrid"
      kwargs:
        geom: "hand_2distph"
        resolution: [0, 1, 2]
  effort_model:
    cls: "Neural"
    kwargs:
      weight: 1e-4
  run_parameters:
    action_sample_freq: 20

rl:
  algorithm: "PPO"
  policy_type: "policies.MultiInputActorCriticPolicyTanhActions"
  policy_kwargs:
    activation_fn: "torch.nn.LeakyReLU"
    net_arch: [256, 256, 256]
    log_std_init: 0.0
    features_extractor_class: "feature_extractor.FeatureExtractor"
    normalize_images: False
  lr: 
    function: "schedule.linear_schedule"
    kwargs:
      initial_value: 5e-5
      min_value: 1e-7
      threshold: 0.8
  total_timesteps: 200_000_000
  device: "cuda"
  num_workers: 1
  nsteps: 400
  batch_size: 100
  target_kl: 1.0
  save_freq: 5_000_000