simulator_name: "mobl_arms_llc_4s_50hz"

simulation:
  bm_model:
    cls: "MoblArms"
    kwargs:
      shoulder_variant: "none"
  task:
    cls: "LowLevelController"
    kwargs:
      joints: ["elv_angle", "shoulder_elv", "shoulder_rot", "elbow_flexion", "pro_sup"]
  perception_modules:
    - cls: "proprioception.BasicWithEndEffectorPosition"
      kwargs:
        end_effector: ["geom", "hand_2distph"]
  run_parameters:
    action_sample_freq: 50
    max_trial_time: 4
    dwell_time: 0.5
  effort_model:
    cls: "Neural"
    kwargs:
      weight: 1e-4

rl:
  algorithm: "PPO"
  policy_type: "policies.MultiInputActorCriticPolicyTanhActions"
  policy_kwargs:
    activation_fn: "torch.nn.LeakyReLU"
    net_arch: [256, 256]
    log_std_init: 0.0
    features_extractor_class: "feature_extractor.FeatureExtractor"
    normalize_images: False
  lr: 
    function: "schedule.linear_schedule"
    kwargs:
      initial_value: 5e-5
      min_value: 1e-7
      threshold: 0.8
  total_timesteps: 200_000_000
  device: "cuda"
  num_workers: 10
  nsteps: 4000
  batch_size: 1000
  target_kl: 1.0
  save_freq: 5_000_000
